Fix/rename dashboard components
TACC/protx pull request #52
Opened 2021-08-31 03:34 UTC by taoteg

## Overview: ##

- All refactored name updates and reduction in code complexity. 
- No visible changes to the app.
- All tests are passing.
- All linting is passing.

## Related Jira tickets: ##

* None

## Summary of Changes: ##

## Testing Steps: ##

1. Run project succesfully.

## UI Photos:

## Notes: ##

2021-08-31 03:37 UTC, taoteg commented
Recommend this get merged into main LAST.

1) 'Update Analytics Dashboard' PR
2) 'Cleanup of ProTx subduir for project' PR
3) This PR 

** May require me running a FF locally off main (after 1 & 2 are merged) and resolving some deltas before this one merges cleanly, but I could be wrong.

2021-09-01 16:46 UTC, nathanfranklin requested changes
The renaming of charts looks good 👍   Its nice to have this refactor and have improved names for components that match up better with how the researchers/end-users are referring to them.

Regarding `DashboardDisplay.js`, there is some issues in the refactor. I put some code suggestions in it and reaching out on slack.


-------

Not related to this PR but feels like DisplaySelectors is the next candidate for house keeping as its the victim of lots of last minute changes.

2021-09-01 16:46 UTC, nathanfranklin commented on client/src/components/ProTx/components/dashboard/DashboardDisplay.js
> +            setGeography('county');
```suggestion
```

2021-09-01 16:46 UTC, nathanfranklin commented on client/src/components/ProTx/components/dashboard/DashboardDisplay.js
> +                  // limitToTopObservedFeatureFields
```suggestion
```

2021-09-01 16:46 UTC, nathanfranklin commented on client/src/components/ProTx/components/dashboard/DashboardDisplay.js
> +            setYear('2019');
```suggestion
```

2021-09-01 16:46 UTC, nathanfranklin commented on client/src/components/ProTx/components/dashboard/DashboardDisplay.js
> +            setMapType('predictiveFeatures');
```suggestion
            setMapType('observedFeatures');
```

This is untested but I'm guessing this is the issue where I am seeing wrong values displayed on map.

2021-09-01 21:56 UTC, nathanfranklin commented on client/src/components/ProTx/components/dashboard/DashboardDisplay.js
> +                  setObservedFeature={setObservedFeature}
```suggestion
                  setObservedFeature={setObservedFeature}
                  setGeography={setGeography}
```

2021-09-01 22:05 UTC, nathanfranklin commented on client/src/components/ProTx/components/dashboard/DashboardDisplay.js
> +                  setMaltreatmentTypes={setMaltreatmentTypes}
```suggestion
```

2021-09-02 14:42 UTC, nathanfranklin approved these changes

2021-09-02 14:43 UTC, nathanfranklin commented
LGTM 👍 

-----
There is a one other suggestion that has no effect on anything https://github.com/TACC/protx/pull/52#discussion_r700606205 but could be committed.  It really reflects that the DisplaySelectors is the next candidate for house keeping.

2021-09-02 22:31 UTC, merged